###eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
###网关端口号建议使用80
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理    
zuul:
  routes:
    api-a:
     ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: antmeite-member
    api-b:
        ### 以 /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: antmeite-order
