###服务启动端口号
server:
  port: 8020
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: antmeite-stock
  #数据库连接信息
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8080/eureka
           
###注册lcn在线模块
tm: 
  manager: 
     url: http://127.0.0.1:8899/tx/manager/